// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_GAMEPROTOCOL_GAMEPROTOCOL_H_
#define FLATBUFFERS_GENERATED_GAMEPROTOCOL_GAMEPROTOCOL_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

namespace GameProtocol {

struct CSLogin;
struct CSLoginBuilder;

struct CSMove;
struct CSMoveBuilder;

struct CSAttack;
struct CSAttackBuilder;

struct CSChat;
struct CSChatBuilder;

struct CSTeleport;
struct CSTeleportBuilder;

struct SCLoginOk;
struct SCLoginOkBuilder;

struct SCMove;
struct SCMoveBuilder;

struct SCPutObject;
struct SCPutObjectBuilder;

struct SCRemoveObject;
struct SCRemoveObjectBuilder;

struct SCChat;
struct SCChatBuilder;

struct SCLoginFail;
struct SCLoginFailBuilder;

struct SCStatusChange;
struct SCStatusChangeBuilder;

struct SCAttack;
struct SCAttackBuilder;

struct SCObstacle;
struct SCObstacleBuilder;

struct CSMessage;
struct CSMessageBuilder;

struct SCMessage;
struct SCMessageBuilder;

enum class CSPacketType : int8_t {
  LOGIN = 1,
  MOVE = 2,
  ATTACK = 3,
  CHAT = 4,
  TELEPORT = 5,
  MIN = LOGIN,
  MAX = TELEPORT
};

inline const CSPacketType (&EnumValuesCSPacketType())[5] {
  static const CSPacketType values[] = {
    CSPacketType::LOGIN,
    CSPacketType::MOVE,
    CSPacketType::ATTACK,
    CSPacketType::CHAT,
    CSPacketType::TELEPORT
  };
  return values;
}

inline const char * const *EnumNamesCSPacketType() {
  static const char * const names[6] = {
    "LOGIN",
    "MOVE",
    "ATTACK",
    "CHAT",
    "TELEPORT",
    nullptr
  };
  return names;
}

inline const char *EnumNameCSPacketType(CSPacketType e) {
  if (::flatbuffers::IsOutRange(e, CSPacketType::LOGIN, CSPacketType::TELEPORT)) return "";
  const size_t index = static_cast<size_t>(e) - static_cast<size_t>(CSPacketType::LOGIN);
  return EnumNamesCSPacketType()[index];
}

enum class SCPacketType : int8_t {
  LOGIN_OK = 1,
  MOVE = 2,
  PUT_OBJECT = 3,
  REMOVE_OBJECT = 4,
  CHAT = 5,
  LOGIN_FAIL = 6,
  STATUS_CHANGE = 7,
  OBSTACLE = 8,
  ATTACK = 9,
  LOGIN_NO = 10,
  MIN = LOGIN_OK,
  MAX = LOGIN_NO
};

inline const SCPacketType (&EnumValuesSCPacketType())[10] {
  static const SCPacketType values[] = {
    SCPacketType::LOGIN_OK,
    SCPacketType::MOVE,
    SCPacketType::PUT_OBJECT,
    SCPacketType::REMOVE_OBJECT,
    SCPacketType::CHAT,
    SCPacketType::LOGIN_FAIL,
    SCPacketType::STATUS_CHANGE,
    SCPacketType::OBSTACLE,
    SCPacketType::ATTACK,
    SCPacketType::LOGIN_NO
  };
  return values;
}

inline const char * const *EnumNamesSCPacketType() {
  static const char * const names[11] = {
    "LOGIN_OK",
    "MOVE",
    "PUT_OBJECT",
    "REMOVE_OBJECT",
    "CHAT",
    "LOGIN_FAIL",
    "STATUS_CHANGE",
    "OBSTACLE",
    "ATTACK",
    "LOGIN_NO",
    nullptr
  };
  return names;
}

inline const char *EnumNameSCPacketType(SCPacketType e) {
  if (::flatbuffers::IsOutRange(e, SCPacketType::LOGIN_OK, SCPacketType::LOGIN_NO)) return "";
  const size_t index = static_cast<size_t>(e) - static_cast<size_t>(SCPacketType::LOGIN_OK);
  return EnumNamesSCPacketType()[index];
}

enum class Direction : int8_t {
  UP = 0,
  DOWN = 1,
  LEFT = 2,
  RIGHT = 3,
  MIN = UP,
  MAX = RIGHT
};

inline const Direction (&EnumValuesDirection())[4] {
  static const Direction values[] = {
    Direction::UP,
    Direction::DOWN,
    Direction::LEFT,
    Direction::RIGHT
  };
  return values;
}

inline const char * const *EnumNamesDirection() {
  static const char * const names[5] = {
    "UP",
    "DOWN",
    "LEFT",
    "RIGHT",
    nullptr
  };
  return names;
}

inline const char *EnumNameDirection(Direction e) {
  if (::flatbuffers::IsOutRange(e, Direction::UP, Direction::RIGHT)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesDirection()[index];
}

enum class ObjectType : int8_t {
  NONE = 0,
  PLAYER = 1,
  NPC_DOG = 2,
  NPC_CAT = 3,
  MIN = NONE,
  MAX = NPC_CAT
};

inline const ObjectType (&EnumValuesObjectType())[4] {
  static const ObjectType values[] = {
    ObjectType::NONE,
    ObjectType::PLAYER,
    ObjectType::NPC_DOG,
    ObjectType::NPC_CAT
  };
  return values;
}

inline const char * const *EnumNamesObjectType() {
  static const char * const names[5] = {
    "NONE",
    "PLAYER",
    "NPC_DOG",
    "NPC_CAT",
    nullptr
  };
  return names;
}

inline const char *EnumNameObjectType(ObjectType e) {
  if (::flatbuffers::IsOutRange(e, ObjectType::NONE, ObjectType::NPC_CAT)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesObjectType()[index];
}

enum class CSPacket : uint8_t {
  NONE = 0,
  CSLogin = 1,
  CSMove = 2,
  CSAttack = 3,
  CSChat = 4,
  CSTeleport = 5,
  MIN = NONE,
  MAX = CSTeleport
};

inline const CSPacket (&EnumValuesCSPacket())[6] {
  static const CSPacket values[] = {
    CSPacket::NONE,
    CSPacket::CSLogin,
    CSPacket::CSMove,
    CSPacket::CSAttack,
    CSPacket::CSChat,
    CSPacket::CSTeleport
  };
  return values;
}

inline const char * const *EnumNamesCSPacket() {
  static const char * const names[7] = {
    "NONE",
    "CSLogin",
    "CSMove",
    "CSAttack",
    "CSChat",
    "CSTeleport",
    nullptr
  };
  return names;
}

inline const char *EnumNameCSPacket(CSPacket e) {
  if (::flatbuffers::IsOutRange(e, CSPacket::NONE, CSPacket::CSTeleport)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesCSPacket()[index];
}

template<typename T> struct CSPacketTraits {
  static const CSPacket enum_value = CSPacket::NONE;
};

template<> struct CSPacketTraits<GameProtocol::CSLogin> {
  static const CSPacket enum_value = CSPacket::CSLogin;
};

template<> struct CSPacketTraits<GameProtocol::CSMove> {
  static const CSPacket enum_value = CSPacket::CSMove;
};

template<> struct CSPacketTraits<GameProtocol::CSAttack> {
  static const CSPacket enum_value = CSPacket::CSAttack;
};

template<> struct CSPacketTraits<GameProtocol::CSChat> {
  static const CSPacket enum_value = CSPacket::CSChat;
};

template<> struct CSPacketTraits<GameProtocol::CSTeleport> {
  static const CSPacket enum_value = CSPacket::CSTeleport;
};

bool VerifyCSPacket(::flatbuffers::Verifier &verifier, const void *obj, CSPacket type);
bool VerifyCSPacketVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<CSPacket> *types);

enum class SCPacket : uint8_t {
  NONE = 0,
  SCLoginOk = 1,
  SCMove = 2,
  SCPutObject = 3,
  SCRemoveObject = 4,
  SCChat = 5,
  SCLoginFail = 6,
  SCStatusChange = 7,
  SCAttack = 8,
  SCObstacle = 9,
  MIN = NONE,
  MAX = SCObstacle
};

inline const SCPacket (&EnumValuesSCPacket())[10] {
  static const SCPacket values[] = {
    SCPacket::NONE,
    SCPacket::SCLoginOk,
    SCPacket::SCMove,
    SCPacket::SCPutObject,
    SCPacket::SCRemoveObject,
    SCPacket::SCChat,
    SCPacket::SCLoginFail,
    SCPacket::SCStatusChange,
    SCPacket::SCAttack,
    SCPacket::SCObstacle
  };
  return values;
}

inline const char * const *EnumNamesSCPacket() {
  static const char * const names[11] = {
    "NONE",
    "SCLoginOk",
    "SCMove",
    "SCPutObject",
    "SCRemoveObject",
    "SCChat",
    "SCLoginFail",
    "SCStatusChange",
    "SCAttack",
    "SCObstacle",
    nullptr
  };
  return names;
}

inline const char *EnumNameSCPacket(SCPacket e) {
  if (::flatbuffers::IsOutRange(e, SCPacket::NONE, SCPacket::SCObstacle)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSCPacket()[index];
}

template<typename T> struct SCPacketTraits {
  static const SCPacket enum_value = SCPacket::NONE;
};

template<> struct SCPacketTraits<GameProtocol::SCLoginOk> {
  static const SCPacket enum_value = SCPacket::SCLoginOk;
};

template<> struct SCPacketTraits<GameProtocol::SCMove> {
  static const SCPacket enum_value = SCPacket::SCMove;
};

template<> struct SCPacketTraits<GameProtocol::SCPutObject> {
  static const SCPacket enum_value = SCPacket::SCPutObject;
};

template<> struct SCPacketTraits<GameProtocol::SCRemoveObject> {
  static const SCPacket enum_value = SCPacket::SCRemoveObject;
};

template<> struct SCPacketTraits<GameProtocol::SCChat> {
  static const SCPacket enum_value = SCPacket::SCChat;
};

template<> struct SCPacketTraits<GameProtocol::SCLoginFail> {
  static const SCPacket enum_value = SCPacket::SCLoginFail;
};

template<> struct SCPacketTraits<GameProtocol::SCStatusChange> {
  static const SCPacket enum_value = SCPacket::SCStatusChange;
};

template<> struct SCPacketTraits<GameProtocol::SCAttack> {
  static const SCPacket enum_value = SCPacket::SCAttack;
};

template<> struct SCPacketTraits<GameProtocol::SCObstacle> {
  static const SCPacket enum_value = SCPacket::SCObstacle;
};

bool VerifySCPacket(::flatbuffers::Verifier &verifier, const void *obj, SCPacket type);
bool VerifySCPacketVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<SCPacket> *types);

struct CSLogin FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CSLoginBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           verifier.EndTable();
  }
};

struct CSLoginBuilder {
  typedef CSLogin Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(CSLogin::VT_NAME, name);
  }
  explicit CSLoginBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CSLogin> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CSLogin>(end);
    fbb_.Required(o, CSLogin::VT_NAME);
    return o;
  }
};

inline ::flatbuffers::Offset<CSLogin> CreateCSLogin(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0) {
  CSLoginBuilder builder_(_fbb);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CSLogin> CreateCSLoginDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return GameProtocol::CreateCSLogin(
      _fbb,
      name__);
}

struct CSMove FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CSMoveBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DIRECTION = 4,
    VT_MOVE_TIME = 6
  };
  GameProtocol::Direction direction() const {
    return static_cast<GameProtocol::Direction>(GetField<int8_t>(VT_DIRECTION, 0));
  }
  int32_t move_time() const {
    return GetField<int32_t>(VT_MOVE_TIME, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_DIRECTION, 1) &&
           VerifyField<int32_t>(verifier, VT_MOVE_TIME, 4) &&
           verifier.EndTable();
  }
};

struct CSMoveBuilder {
  typedef CSMove Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_direction(GameProtocol::Direction direction) {
    fbb_.AddElement<int8_t>(CSMove::VT_DIRECTION, static_cast<int8_t>(direction), 0);
  }
  void add_move_time(int32_t move_time) {
    fbb_.AddElement<int32_t>(CSMove::VT_MOVE_TIME, move_time, 0);
  }
  explicit CSMoveBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CSMove> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CSMove>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CSMove> CreateCSMove(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    GameProtocol::Direction direction = GameProtocol::Direction::UP,
    int32_t move_time = 0) {
  CSMoveBuilder builder_(_fbb);
  builder_.add_move_time(move_time);
  builder_.add_direction(direction);
  return builder_.Finish();
}

struct CSAttack FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CSAttackBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TARGET_ID = 4
  };
  int32_t target_id() const {
    return GetField<int32_t>(VT_TARGET_ID, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_TARGET_ID, 4) &&
           verifier.EndTable();
  }
};

struct CSAttackBuilder {
  typedef CSAttack Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_target_id(int32_t target_id) {
    fbb_.AddElement<int32_t>(CSAttack::VT_TARGET_ID, target_id, 0);
  }
  explicit CSAttackBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CSAttack> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CSAttack>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CSAttack> CreateCSAttack(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t target_id = 0) {
  CSAttackBuilder builder_(_fbb);
  builder_.add_target_id(target_id);
  return builder_.Finish();
}

struct CSChat FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CSChatBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MESSAGE = 4
  };
  const ::flatbuffers::String *message() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MESSAGE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_MESSAGE) &&
           verifier.VerifyString(message()) &&
           verifier.EndTable();
  }
};

struct CSChatBuilder {
  typedef CSChat Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_message(::flatbuffers::Offset<::flatbuffers::String> message) {
    fbb_.AddOffset(CSChat::VT_MESSAGE, message);
  }
  explicit CSChatBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CSChat> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CSChat>(end);
    fbb_.Required(o, CSChat::VT_MESSAGE);
    return o;
  }
};

inline ::flatbuffers::Offset<CSChat> CreateCSChat(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> message = 0) {
  CSChatBuilder builder_(_fbb);
  builder_.add_message(message);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CSChat> CreateCSChatDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *message = nullptr) {
  auto message__ = message ? _fbb.CreateString(message) : 0;
  return GameProtocol::CreateCSChat(
      _fbb,
      message__);
}

struct CSTeleport FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CSTeleportBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct CSTeleportBuilder {
  typedef CSTeleport Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit CSTeleportBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CSTeleport> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CSTeleport>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CSTeleport> CreateCSTeleport(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  CSTeleportBuilder builder_(_fbb);
  return builder_.Finish();
}

struct SCLoginOk FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SCLoginOkBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_X = 6,
    VT_Y = 8,
    VT_LEVEL = 10,
    VT_HP = 12,
    VT_MAXHP = 14,
    VT_EXP = 16
  };
  int32_t id() const {
    return GetField<int32_t>(VT_ID, 0);
  }
  int16_t x() const {
    return GetField<int16_t>(VT_X, 0);
  }
  int16_t y() const {
    return GetField<int16_t>(VT_Y, 0);
  }
  int16_t level() const {
    return GetField<int16_t>(VT_LEVEL, 0);
  }
  int16_t hp() const {
    return GetField<int16_t>(VT_HP, 0);
  }
  int16_t maxhp() const {
    return GetField<int16_t>(VT_MAXHP, 0);
  }
  int32_t exp() const {
    return GetField<int32_t>(VT_EXP, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_ID, 4) &&
           VerifyField<int16_t>(verifier, VT_X, 2) &&
           VerifyField<int16_t>(verifier, VT_Y, 2) &&
           VerifyField<int16_t>(verifier, VT_LEVEL, 2) &&
           VerifyField<int16_t>(verifier, VT_HP, 2) &&
           VerifyField<int16_t>(verifier, VT_MAXHP, 2) &&
           VerifyField<int32_t>(verifier, VT_EXP, 4) &&
           verifier.EndTable();
  }
};

struct SCLoginOkBuilder {
  typedef SCLoginOk Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(int32_t id) {
    fbb_.AddElement<int32_t>(SCLoginOk::VT_ID, id, 0);
  }
  void add_x(int16_t x) {
    fbb_.AddElement<int16_t>(SCLoginOk::VT_X, x, 0);
  }
  void add_y(int16_t y) {
    fbb_.AddElement<int16_t>(SCLoginOk::VT_Y, y, 0);
  }
  void add_level(int16_t level) {
    fbb_.AddElement<int16_t>(SCLoginOk::VT_LEVEL, level, 0);
  }
  void add_hp(int16_t hp) {
    fbb_.AddElement<int16_t>(SCLoginOk::VT_HP, hp, 0);
  }
  void add_maxhp(int16_t maxhp) {
    fbb_.AddElement<int16_t>(SCLoginOk::VT_MAXHP, maxhp, 0);
  }
  void add_exp(int32_t exp) {
    fbb_.AddElement<int32_t>(SCLoginOk::VT_EXP, exp, 0);
  }
  explicit SCLoginOkBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SCLoginOk> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SCLoginOk>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SCLoginOk> CreateSCLoginOk(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t id = 0,
    int16_t x = 0,
    int16_t y = 0,
    int16_t level = 0,
    int16_t hp = 0,
    int16_t maxhp = 0,
    int32_t exp = 0) {
  SCLoginOkBuilder builder_(_fbb);
  builder_.add_exp(exp);
  builder_.add_id(id);
  builder_.add_maxhp(maxhp);
  builder_.add_hp(hp);
  builder_.add_level(level);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

struct SCMove FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SCMoveBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_HP = 6,
    VT_X = 8,
    VT_Y = 10,
    VT_MOVE_TIME = 12
  };
  int32_t id() const {
    return GetField<int32_t>(VT_ID, 0);
  }
  int32_t hp() const {
    return GetField<int32_t>(VT_HP, 0);
  }
  int16_t x() const {
    return GetField<int16_t>(VT_X, 0);
  }
  int16_t y() const {
    return GetField<int16_t>(VT_Y, 0);
  }
  int32_t move_time() const {
    return GetField<int32_t>(VT_MOVE_TIME, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_ID, 4) &&
           VerifyField<int32_t>(verifier, VT_HP, 4) &&
           VerifyField<int16_t>(verifier, VT_X, 2) &&
           VerifyField<int16_t>(verifier, VT_Y, 2) &&
           VerifyField<int32_t>(verifier, VT_MOVE_TIME, 4) &&
           verifier.EndTable();
  }
};

struct SCMoveBuilder {
  typedef SCMove Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(int32_t id) {
    fbb_.AddElement<int32_t>(SCMove::VT_ID, id, 0);
  }
  void add_hp(int32_t hp) {
    fbb_.AddElement<int32_t>(SCMove::VT_HP, hp, 0);
  }
  void add_x(int16_t x) {
    fbb_.AddElement<int16_t>(SCMove::VT_X, x, 0);
  }
  void add_y(int16_t y) {
    fbb_.AddElement<int16_t>(SCMove::VT_Y, y, 0);
  }
  void add_move_time(int32_t move_time) {
    fbb_.AddElement<int32_t>(SCMove::VT_MOVE_TIME, move_time, 0);
  }
  explicit SCMoveBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SCMove> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SCMove>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SCMove> CreateSCMove(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t id = 0,
    int32_t hp = 0,
    int16_t x = 0,
    int16_t y = 0,
    int32_t move_time = 0) {
  SCMoveBuilder builder_(_fbb);
  builder_.add_move_time(move_time);
  builder_.add_hp(hp);
  builder_.add_id(id);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

struct SCPutObject FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SCPutObjectBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_X = 6,
    VT_Y = 8,
    VT_HP = 10,
    VT_OBJECT_TYPE = 12,
    VT_NAME = 14
  };
  int32_t id() const {
    return GetField<int32_t>(VT_ID, 0);
  }
  int16_t x() const {
    return GetField<int16_t>(VT_X, 0);
  }
  int16_t y() const {
    return GetField<int16_t>(VT_Y, 0);
  }
  int32_t hp() const {
    return GetField<int32_t>(VT_HP, 0);
  }
  GameProtocol::ObjectType object_type() const {
    return static_cast<GameProtocol::ObjectType>(GetField<int8_t>(VT_OBJECT_TYPE, 0));
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_ID, 4) &&
           VerifyField<int16_t>(verifier, VT_X, 2) &&
           VerifyField<int16_t>(verifier, VT_Y, 2) &&
           VerifyField<int32_t>(verifier, VT_HP, 4) &&
           VerifyField<int8_t>(verifier, VT_OBJECT_TYPE, 1) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           verifier.EndTable();
  }
};

struct SCPutObjectBuilder {
  typedef SCPutObject Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(int32_t id) {
    fbb_.AddElement<int32_t>(SCPutObject::VT_ID, id, 0);
  }
  void add_x(int16_t x) {
    fbb_.AddElement<int16_t>(SCPutObject::VT_X, x, 0);
  }
  void add_y(int16_t y) {
    fbb_.AddElement<int16_t>(SCPutObject::VT_Y, y, 0);
  }
  void add_hp(int32_t hp) {
    fbb_.AddElement<int32_t>(SCPutObject::VT_HP, hp, 0);
  }
  void add_object_type(GameProtocol::ObjectType object_type) {
    fbb_.AddElement<int8_t>(SCPutObject::VT_OBJECT_TYPE, static_cast<int8_t>(object_type), 0);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(SCPutObject::VT_NAME, name);
  }
  explicit SCPutObjectBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SCPutObject> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SCPutObject>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SCPutObject> CreateSCPutObject(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t id = 0,
    int16_t x = 0,
    int16_t y = 0,
    int32_t hp = 0,
    GameProtocol::ObjectType object_type = GameProtocol::ObjectType::NONE,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0) {
  SCPutObjectBuilder builder_(_fbb);
  builder_.add_name(name);
  builder_.add_hp(hp);
  builder_.add_id(id);
  builder_.add_y(y);
  builder_.add_x(x);
  builder_.add_object_type(object_type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SCPutObject> CreateSCPutObjectDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t id = 0,
    int16_t x = 0,
    int16_t y = 0,
    int32_t hp = 0,
    GameProtocol::ObjectType object_type = GameProtocol::ObjectType::NONE,
    const char *name = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return GameProtocol::CreateSCPutObject(
      _fbb,
      id,
      x,
      y,
      hp,
      object_type,
      name__);
}

struct SCRemoveObject FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SCRemoveObjectBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4
  };
  int32_t id() const {
    return GetField<int32_t>(VT_ID, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_ID, 4) &&
           verifier.EndTable();
  }
};

struct SCRemoveObjectBuilder {
  typedef SCRemoveObject Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(int32_t id) {
    fbb_.AddElement<int32_t>(SCRemoveObject::VT_ID, id, 0);
  }
  explicit SCRemoveObjectBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SCRemoveObject> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SCRemoveObject>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SCRemoveObject> CreateSCRemoveObject(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t id = 0) {
  SCRemoveObjectBuilder builder_(_fbb);
  builder_.add_id(id);
  return builder_.Finish();
}

struct SCChat FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SCChatBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_MESSAGE = 6
  };
  int32_t id() const {
    return GetField<int32_t>(VT_ID, 0);
  }
  const ::flatbuffers::String *message() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MESSAGE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_ID, 4) &&
           VerifyOffsetRequired(verifier, VT_MESSAGE) &&
           verifier.VerifyString(message()) &&
           verifier.EndTable();
  }
};

struct SCChatBuilder {
  typedef SCChat Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(int32_t id) {
    fbb_.AddElement<int32_t>(SCChat::VT_ID, id, 0);
  }
  void add_message(::flatbuffers::Offset<::flatbuffers::String> message) {
    fbb_.AddOffset(SCChat::VT_MESSAGE, message);
  }
  explicit SCChatBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SCChat> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SCChat>(end);
    fbb_.Required(o, SCChat::VT_MESSAGE);
    return o;
  }
};

inline ::flatbuffers::Offset<SCChat> CreateSCChat(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> message = 0) {
  SCChatBuilder builder_(_fbb);
  builder_.add_message(message);
  builder_.add_id(id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SCChat> CreateSCChatDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t id = 0,
    const char *message = nullptr) {
  auto message__ = message ? _fbb.CreateString(message) : 0;
  return GameProtocol::CreateSCChat(
      _fbb,
      id,
      message__);
}

struct SCLoginFail FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SCLoginFailBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_REASON = 4
  };
  int32_t reason() const {
    return GetField<int32_t>(VT_REASON, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_REASON, 4) &&
           verifier.EndTable();
  }
};

struct SCLoginFailBuilder {
  typedef SCLoginFail Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_reason(int32_t reason) {
    fbb_.AddElement<int32_t>(SCLoginFail::VT_REASON, reason, 0);
  }
  explicit SCLoginFailBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SCLoginFail> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SCLoginFail>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SCLoginFail> CreateSCLoginFail(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t reason = 0) {
  SCLoginFailBuilder builder_(_fbb);
  builder_.add_reason(reason);
  return builder_.Finish();
}

struct SCStatusChange FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SCStatusChangeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_LEVEL = 4,
    VT_HP = 6,
    VT_MAXHP = 8,
    VT_EXP = 10
  };
  int16_t level() const {
    return GetField<int16_t>(VT_LEVEL, 0);
  }
  int16_t hp() const {
    return GetField<int16_t>(VT_HP, 0);
  }
  int16_t maxhp() const {
    return GetField<int16_t>(VT_MAXHP, 0);
  }
  int32_t exp() const {
    return GetField<int32_t>(VT_EXP, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int16_t>(verifier, VT_LEVEL, 2) &&
           VerifyField<int16_t>(verifier, VT_HP, 2) &&
           VerifyField<int16_t>(verifier, VT_MAXHP, 2) &&
           VerifyField<int32_t>(verifier, VT_EXP, 4) &&
           verifier.EndTable();
  }
};

struct SCStatusChangeBuilder {
  typedef SCStatusChange Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_level(int16_t level) {
    fbb_.AddElement<int16_t>(SCStatusChange::VT_LEVEL, level, 0);
  }
  void add_hp(int16_t hp) {
    fbb_.AddElement<int16_t>(SCStatusChange::VT_HP, hp, 0);
  }
  void add_maxhp(int16_t maxhp) {
    fbb_.AddElement<int16_t>(SCStatusChange::VT_MAXHP, maxhp, 0);
  }
  void add_exp(int32_t exp) {
    fbb_.AddElement<int32_t>(SCStatusChange::VT_EXP, exp, 0);
  }
  explicit SCStatusChangeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SCStatusChange> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SCStatusChange>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SCStatusChange> CreateSCStatusChange(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int16_t level = 0,
    int16_t hp = 0,
    int16_t maxhp = 0,
    int32_t exp = 0) {
  SCStatusChangeBuilder builder_(_fbb);
  builder_.add_exp(exp);
  builder_.add_maxhp(maxhp);
  builder_.add_hp(hp);
  builder_.add_level(level);
  return builder_.Finish();
}

struct SCAttack FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SCAttackBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_X = 6,
    VT_Y = 8,
    VT_HP = 10,
    VT_EXP = 12
  };
  int32_t id() const {
    return GetField<int32_t>(VT_ID, 0);
  }
  int16_t x() const {
    return GetField<int16_t>(VT_X, 0);
  }
  int16_t y() const {
    return GetField<int16_t>(VT_Y, 0);
  }
  int16_t hp() const {
    return GetField<int16_t>(VT_HP, 0);
  }
  int32_t exp() const {
    return GetField<int32_t>(VT_EXP, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_ID, 4) &&
           VerifyField<int16_t>(verifier, VT_X, 2) &&
           VerifyField<int16_t>(verifier, VT_Y, 2) &&
           VerifyField<int16_t>(verifier, VT_HP, 2) &&
           VerifyField<int32_t>(verifier, VT_EXP, 4) &&
           verifier.EndTable();
  }
};

struct SCAttackBuilder {
  typedef SCAttack Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(int32_t id) {
    fbb_.AddElement<int32_t>(SCAttack::VT_ID, id, 0);
  }
  void add_x(int16_t x) {
    fbb_.AddElement<int16_t>(SCAttack::VT_X, x, 0);
  }
  void add_y(int16_t y) {
    fbb_.AddElement<int16_t>(SCAttack::VT_Y, y, 0);
  }
  void add_hp(int16_t hp) {
    fbb_.AddElement<int16_t>(SCAttack::VT_HP, hp, 0);
  }
  void add_exp(int32_t exp) {
    fbb_.AddElement<int32_t>(SCAttack::VT_EXP, exp, 0);
  }
  explicit SCAttackBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SCAttack> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SCAttack>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SCAttack> CreateSCAttack(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t id = 0,
    int16_t x = 0,
    int16_t y = 0,
    int16_t hp = 0,
    int32_t exp = 0) {
  SCAttackBuilder builder_(_fbb);
  builder_.add_exp(exp);
  builder_.add_id(id);
  builder_.add_hp(hp);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

struct SCObstacle FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SCObstacleBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_X = 6,
    VT_Y = 8
  };
  int32_t id() const {
    return GetField<int32_t>(VT_ID, 0);
  }
  int32_t x() const {
    return GetField<int32_t>(VT_X, 0);
  }
  int32_t y() const {
    return GetField<int32_t>(VT_Y, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_ID, 4) &&
           VerifyField<int32_t>(verifier, VT_X, 4) &&
           VerifyField<int32_t>(verifier, VT_Y, 4) &&
           verifier.EndTable();
  }
};

struct SCObstacleBuilder {
  typedef SCObstacle Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(int32_t id) {
    fbb_.AddElement<int32_t>(SCObstacle::VT_ID, id, 0);
  }
  void add_x(int32_t x) {
    fbb_.AddElement<int32_t>(SCObstacle::VT_X, x, 0);
  }
  void add_y(int32_t y) {
    fbb_.AddElement<int32_t>(SCObstacle::VT_Y, y, 0);
  }
  explicit SCObstacleBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SCObstacle> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SCObstacle>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SCObstacle> CreateSCObstacle(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t id = 0,
    int32_t x = 0,
    int32_t y = 0) {
  SCObstacleBuilder builder_(_fbb);
  builder_.add_y(y);
  builder_.add_x(x);
  builder_.add_id(id);
  return builder_.Finish();
}

struct CSMessage FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CSMessageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PACKET_TYPE = 4,
    VT_PACKET = 6
  };
  GameProtocol::CSPacket packet_type() const {
    return static_cast<GameProtocol::CSPacket>(GetField<uint8_t>(VT_PACKET_TYPE, 0));
  }
  const void *packet() const {
    return GetPointer<const void *>(VT_PACKET);
  }
  template<typename T> const T *packet_as() const;
  const GameProtocol::CSLogin *packet_as_CSLogin() const {
    return packet_type() == GameProtocol::CSPacket::CSLogin ? static_cast<const GameProtocol::CSLogin *>(packet()) : nullptr;
  }
  const GameProtocol::CSMove *packet_as_CSMove() const {
    return packet_type() == GameProtocol::CSPacket::CSMove ? static_cast<const GameProtocol::CSMove *>(packet()) : nullptr;
  }
  const GameProtocol::CSAttack *packet_as_CSAttack() const {
    return packet_type() == GameProtocol::CSPacket::CSAttack ? static_cast<const GameProtocol::CSAttack *>(packet()) : nullptr;
  }
  const GameProtocol::CSChat *packet_as_CSChat() const {
    return packet_type() == GameProtocol::CSPacket::CSChat ? static_cast<const GameProtocol::CSChat *>(packet()) : nullptr;
  }
  const GameProtocol::CSTeleport *packet_as_CSTeleport() const {
    return packet_type() == GameProtocol::CSPacket::CSTeleport ? static_cast<const GameProtocol::CSTeleport *>(packet()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_PACKET_TYPE, 1) &&
           VerifyOffset(verifier, VT_PACKET) &&
           VerifyCSPacket(verifier, packet(), packet_type()) &&
           verifier.EndTable();
  }
};

template<> inline const GameProtocol::CSLogin *CSMessage::packet_as<GameProtocol::CSLogin>() const {
  return packet_as_CSLogin();
}

template<> inline const GameProtocol::CSMove *CSMessage::packet_as<GameProtocol::CSMove>() const {
  return packet_as_CSMove();
}

template<> inline const GameProtocol::CSAttack *CSMessage::packet_as<GameProtocol::CSAttack>() const {
  return packet_as_CSAttack();
}

template<> inline const GameProtocol::CSChat *CSMessage::packet_as<GameProtocol::CSChat>() const {
  return packet_as_CSChat();
}

template<> inline const GameProtocol::CSTeleport *CSMessage::packet_as<GameProtocol::CSTeleport>() const {
  return packet_as_CSTeleport();
}

struct CSMessageBuilder {
  typedef CSMessage Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_packet_type(GameProtocol::CSPacket packet_type) {
    fbb_.AddElement<uint8_t>(CSMessage::VT_PACKET_TYPE, static_cast<uint8_t>(packet_type), 0);
  }
  void add_packet(::flatbuffers::Offset<void> packet) {
    fbb_.AddOffset(CSMessage::VT_PACKET, packet);
  }
  explicit CSMessageBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CSMessage> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CSMessage>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CSMessage> CreateCSMessage(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    GameProtocol::CSPacket packet_type = GameProtocol::CSPacket::NONE,
    ::flatbuffers::Offset<void> packet = 0) {
  CSMessageBuilder builder_(_fbb);
  builder_.add_packet(packet);
  builder_.add_packet_type(packet_type);
  return builder_.Finish();
}

struct SCMessage FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SCMessageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PACKET_TYPE = 4,
    VT_PACKET = 6
  };
  GameProtocol::SCPacket packet_type() const {
    return static_cast<GameProtocol::SCPacket>(GetField<uint8_t>(VT_PACKET_TYPE, 0));
  }
  const void *packet() const {
    return GetPointer<const void *>(VT_PACKET);
  }
  template<typename T> const T *packet_as() const;
  const GameProtocol::SCLoginOk *packet_as_SCLoginOk() const {
    return packet_type() == GameProtocol::SCPacket::SCLoginOk ? static_cast<const GameProtocol::SCLoginOk *>(packet()) : nullptr;
  }
  const GameProtocol::SCMove *packet_as_SCMove() const {
    return packet_type() == GameProtocol::SCPacket::SCMove ? static_cast<const GameProtocol::SCMove *>(packet()) : nullptr;
  }
  const GameProtocol::SCPutObject *packet_as_SCPutObject() const {
    return packet_type() == GameProtocol::SCPacket::SCPutObject ? static_cast<const GameProtocol::SCPutObject *>(packet()) : nullptr;
  }
  const GameProtocol::SCRemoveObject *packet_as_SCRemoveObject() const {
    return packet_type() == GameProtocol::SCPacket::SCRemoveObject ? static_cast<const GameProtocol::SCRemoveObject *>(packet()) : nullptr;
  }
  const GameProtocol::SCChat *packet_as_SCChat() const {
    return packet_type() == GameProtocol::SCPacket::SCChat ? static_cast<const GameProtocol::SCChat *>(packet()) : nullptr;
  }
  const GameProtocol::SCLoginFail *packet_as_SCLoginFail() const {
    return packet_type() == GameProtocol::SCPacket::SCLoginFail ? static_cast<const GameProtocol::SCLoginFail *>(packet()) : nullptr;
  }
  const GameProtocol::SCStatusChange *packet_as_SCStatusChange() const {
    return packet_type() == GameProtocol::SCPacket::SCStatusChange ? static_cast<const GameProtocol::SCStatusChange *>(packet()) : nullptr;
  }
  const GameProtocol::SCAttack *packet_as_SCAttack() const {
    return packet_type() == GameProtocol::SCPacket::SCAttack ? static_cast<const GameProtocol::SCAttack *>(packet()) : nullptr;
  }
  const GameProtocol::SCObstacle *packet_as_SCObstacle() const {
    return packet_type() == GameProtocol::SCPacket::SCObstacle ? static_cast<const GameProtocol::SCObstacle *>(packet()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_PACKET_TYPE, 1) &&
           VerifyOffset(verifier, VT_PACKET) &&
           VerifySCPacket(verifier, packet(), packet_type()) &&
           verifier.EndTable();
  }
};

template<> inline const GameProtocol::SCLoginOk *SCMessage::packet_as<GameProtocol::SCLoginOk>() const {
  return packet_as_SCLoginOk();
}

template<> inline const GameProtocol::SCMove *SCMessage::packet_as<GameProtocol::SCMove>() const {
  return packet_as_SCMove();
}

template<> inline const GameProtocol::SCPutObject *SCMessage::packet_as<GameProtocol::SCPutObject>() const {
  return packet_as_SCPutObject();
}

template<> inline const GameProtocol::SCRemoveObject *SCMessage::packet_as<GameProtocol::SCRemoveObject>() const {
  return packet_as_SCRemoveObject();
}

template<> inline const GameProtocol::SCChat *SCMessage::packet_as<GameProtocol::SCChat>() const {
  return packet_as_SCChat();
}

template<> inline const GameProtocol::SCLoginFail *SCMessage::packet_as<GameProtocol::SCLoginFail>() const {
  return packet_as_SCLoginFail();
}

template<> inline const GameProtocol::SCStatusChange *SCMessage::packet_as<GameProtocol::SCStatusChange>() const {
  return packet_as_SCStatusChange();
}

template<> inline const GameProtocol::SCAttack *SCMessage::packet_as<GameProtocol::SCAttack>() const {
  return packet_as_SCAttack();
}

template<> inline const GameProtocol::SCObstacle *SCMessage::packet_as<GameProtocol::SCObstacle>() const {
  return packet_as_SCObstacle();
}

struct SCMessageBuilder {
  typedef SCMessage Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_packet_type(GameProtocol::SCPacket packet_type) {
    fbb_.AddElement<uint8_t>(SCMessage::VT_PACKET_TYPE, static_cast<uint8_t>(packet_type), 0);
  }
  void add_packet(::flatbuffers::Offset<void> packet) {
    fbb_.AddOffset(SCMessage::VT_PACKET, packet);
  }
  explicit SCMessageBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SCMessage> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SCMessage>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SCMessage> CreateSCMessage(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    GameProtocol::SCPacket packet_type = GameProtocol::SCPacket::NONE,
    ::flatbuffers::Offset<void> packet = 0) {
  SCMessageBuilder builder_(_fbb);
  builder_.add_packet(packet);
  builder_.add_packet_type(packet_type);
  return builder_.Finish();
}

inline bool VerifyCSPacket(::flatbuffers::Verifier &verifier, const void *obj, CSPacket type) {
  switch (type) {
    case CSPacket::NONE: {
      return true;
    }
    case CSPacket::CSLogin: {
      auto ptr = reinterpret_cast<const GameProtocol::CSLogin *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case CSPacket::CSMove: {
      auto ptr = reinterpret_cast<const GameProtocol::CSMove *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case CSPacket::CSAttack: {
      auto ptr = reinterpret_cast<const GameProtocol::CSAttack *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case CSPacket::CSChat: {
      auto ptr = reinterpret_cast<const GameProtocol::CSChat *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case CSPacket::CSTeleport: {
      auto ptr = reinterpret_cast<const GameProtocol::CSTeleport *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyCSPacketVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<CSPacket> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyCSPacket(
        verifier,  values->Get(i), types->GetEnum<CSPacket>(i))) {
      return false;
    }
  }
  return true;
}

inline bool VerifySCPacket(::flatbuffers::Verifier &verifier, const void *obj, SCPacket type) {
  switch (type) {
    case SCPacket::NONE: {
      return true;
    }
    case SCPacket::SCLoginOk: {
      auto ptr = reinterpret_cast<const GameProtocol::SCLoginOk *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case SCPacket::SCMove: {
      auto ptr = reinterpret_cast<const GameProtocol::SCMove *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case SCPacket::SCPutObject: {
      auto ptr = reinterpret_cast<const GameProtocol::SCPutObject *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case SCPacket::SCRemoveObject: {
      auto ptr = reinterpret_cast<const GameProtocol::SCRemoveObject *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case SCPacket::SCChat: {
      auto ptr = reinterpret_cast<const GameProtocol::SCChat *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case SCPacket::SCLoginFail: {
      auto ptr = reinterpret_cast<const GameProtocol::SCLoginFail *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case SCPacket::SCStatusChange: {
      auto ptr = reinterpret_cast<const GameProtocol::SCStatusChange *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case SCPacket::SCAttack: {
      auto ptr = reinterpret_cast<const GameProtocol::SCAttack *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case SCPacket::SCObstacle: {
      auto ptr = reinterpret_cast<const GameProtocol::SCObstacle *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifySCPacketVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<SCPacket> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifySCPacket(
        verifier,  values->Get(i), types->GetEnum<SCPacket>(i))) {
      return false;
    }
  }
  return true;
}

inline const GameProtocol::SCMessage *GetSCMessage(const void *buf) {
  return ::flatbuffers::GetRoot<GameProtocol::SCMessage>(buf);
}

inline const GameProtocol::SCMessage *GetSizePrefixedSCMessage(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<GameProtocol::SCMessage>(buf);
}

inline bool VerifySCMessageBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<GameProtocol::SCMessage>(nullptr);
}

inline bool VerifySizePrefixedSCMessageBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<GameProtocol::SCMessage>(nullptr);
}

inline void FinishSCMessageBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<GameProtocol::SCMessage> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedSCMessageBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<GameProtocol::SCMessage> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace GameProtocol

#endif  // FLATBUFFERS_GENERATED_GAMEPROTOCOL_GAMEPROTOCOL_H_
