// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_GAMEPROTOCOL_GAMEPROTOCOL_H_
#define FLATBUFFERS_GENERATED_GAMEPROTOCOL_GAMEPROTOCOL_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

namespace GameProtocol {

struct MPositionXY;
struct MPositionXYBuilder;

struct MPositionXYDir;
struct MPositionXYDirBuilder;

struct CSLogin;
struct CSLoginBuilder;

struct CSPlayerMoveRequest;
struct CSPlayerMoveRequestBuilder;

struct SCPlayerMoveResponse;
struct SCPlayerMoveResponseBuilder;

struct CSPlayerAttackRequest;
struct CSPlayerAttackRequestBuilder;

struct SCPlayerAttackResponse;
struct SCPlayerAttackResponseBuilder;

struct CSPlayerChattingRequest;
struct CSPlayerChattingRequestBuilder;

struct SCPlayerChattingResponse;
struct SCPlayerChattingResponseBuilder;

struct CSRandomTeleportRequest;
struct CSRandomTeleportRequestBuilder;

enum EPacketProtocol : int32_t {
  EPacketProtocol_CS_LoginRequest = 101,
  EPacketProtocol_SDB_LoginRequest = 102,
  EPacketProtocol_DBS_LoginResponse = 103,
  EPacketProtocol_SC_LoginResponse = 104,
  EPacketProtocol_CS_PlayerMoveRequest = 201,
  EPacketProtocol_SC_PlayerMoveResponse = 202,
  EPacketProtocol_CS_PlayerTeleportRequest = 203,
  EPacketProtocol_SC_PlayerTeleportResponse = 204,
  EPacketProtocol_CS_PlayerAttackRequest = 205,
  EPacketProtocol_SC_PlayerAttackResponse = 206,
  EPacketProtocol_CS_PlayerChattingRequest = 301,
  EPacketProtocol_SC_PlayerChattingResponse = 302,
  EPacketProtocol_CS_RandomTeleportRequest = 401,
  EPacketProtocol_Max = 402,
  EPacketProtocol_MIN = EPacketProtocol_CS_LoginRequest,
  EPacketProtocol_MAX = EPacketProtocol_Max
};

inline const EPacketProtocol (&EnumValuesEPacketProtocol())[14] {
  static const EPacketProtocol values[] = {
    EPacketProtocol_CS_LoginRequest,
    EPacketProtocol_SDB_LoginRequest,
    EPacketProtocol_DBS_LoginResponse,
    EPacketProtocol_SC_LoginResponse,
    EPacketProtocol_CS_PlayerMoveRequest,
    EPacketProtocol_SC_PlayerMoveResponse,
    EPacketProtocol_CS_PlayerTeleportRequest,
    EPacketProtocol_SC_PlayerTeleportResponse,
    EPacketProtocol_CS_PlayerAttackRequest,
    EPacketProtocol_SC_PlayerAttackResponse,
    EPacketProtocol_CS_PlayerChattingRequest,
    EPacketProtocol_SC_PlayerChattingResponse,
    EPacketProtocol_CS_RandomTeleportRequest,
    EPacketProtocol_Max
  };
  return values;
}

inline const char *EnumNameEPacketProtocol(EPacketProtocol e) {
  switch (e) {
    case EPacketProtocol_CS_LoginRequest: return "CS_LoginRequest";
    case EPacketProtocol_SDB_LoginRequest: return "SDB_LoginRequest";
    case EPacketProtocol_DBS_LoginResponse: return "DBS_LoginResponse";
    case EPacketProtocol_SC_LoginResponse: return "SC_LoginResponse";
    case EPacketProtocol_CS_PlayerMoveRequest: return "CS_PlayerMoveRequest";
    case EPacketProtocol_SC_PlayerMoveResponse: return "SC_PlayerMoveResponse";
    case EPacketProtocol_CS_PlayerTeleportRequest: return "CS_PlayerTeleportRequest";
    case EPacketProtocol_SC_PlayerTeleportResponse: return "SC_PlayerTeleportResponse";
    case EPacketProtocol_CS_PlayerAttackRequest: return "CS_PlayerAttackRequest";
    case EPacketProtocol_SC_PlayerAttackResponse: return "SC_PlayerAttackResponse";
    case EPacketProtocol_CS_PlayerChattingRequest: return "CS_PlayerChattingRequest";
    case EPacketProtocol_SC_PlayerChattingResponse: return "SC_PlayerChattingResponse";
    case EPacketProtocol_CS_RandomTeleportRequest: return "CS_RandomTeleportRequest";
    case EPacketProtocol_Max: return "Max";
    default: return "";
  }
}

enum Direction : int8_t {
  Direction_UP = 0,
  Direction_DOWN = 1,
  Direction_LEFT = 2,
  Direction_RIGHT = 3,
  Direction_MIN = Direction_UP,
  Direction_MAX = Direction_RIGHT
};

inline const Direction (&EnumValuesDirection())[4] {
  static const Direction values[] = {
    Direction_UP,
    Direction_DOWN,
    Direction_LEFT,
    Direction_RIGHT
  };
  return values;
}

inline const char * const *EnumNamesDirection() {
  static const char * const names[5] = {
    "UP",
    "DOWN",
    "LEFT",
    "RIGHT",
    nullptr
  };
  return names;
}

inline const char *EnumNameDirection(Direction e) {
  if (::flatbuffers::IsOutRange(e, Direction_UP, Direction_RIGHT)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesDirection()[index];
}

enum EErrorMsg : int32_t {
  EErrorMsg_EF_NONE = 0,
  EErrorMsg_EF_FAIL_WRONG_REQ = 10001,
  EErrorMsg_EF_FAIL_DUPLICATE_NAME = 10002,
  EErrorMsg_EF_MAX = 10003,
  EErrorMsg_MIN = EErrorMsg_EF_NONE,
  EErrorMsg_MAX = EErrorMsg_EF_MAX
};

inline const EErrorMsg (&EnumValuesEErrorMsg())[4] {
  static const EErrorMsg values[] = {
    EErrorMsg_EF_NONE,
    EErrorMsg_EF_FAIL_WRONG_REQ,
    EErrorMsg_EF_FAIL_DUPLICATE_NAME,
    EErrorMsg_EF_MAX
  };
  return values;
}

inline const char *EnumNameEErrorMsg(EErrorMsg e) {
  switch (e) {
    case EErrorMsg_EF_NONE: return "EF_NONE";
    case EErrorMsg_EF_FAIL_WRONG_REQ: return "EF_FAIL_WRONG_REQ";
    case EErrorMsg_EF_FAIL_DUPLICATE_NAME: return "EF_FAIL_DUPLICATE_NAME";
    case EErrorMsg_EF_MAX: return "EF_MAX";
    default: return "";
  }
}

struct MPositionXY FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MPositionXYBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_Y = 6
  };
  int16_t x() const {
    return GetField<int16_t>(VT_X, 0);
  }
  int16_t y() const {
    return GetField<int16_t>(VT_Y, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int16_t>(verifier, VT_X, 2) &&
           VerifyField<int16_t>(verifier, VT_Y, 2) &&
           verifier.EndTable();
  }
};

struct MPositionXYBuilder {
  typedef MPositionXY Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x(int16_t x) {
    fbb_.AddElement<int16_t>(MPositionXY::VT_X, x, 0);
  }
  void add_y(int16_t y) {
    fbb_.AddElement<int16_t>(MPositionXY::VT_Y, y, 0);
  }
  explicit MPositionXYBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MPositionXY> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MPositionXY>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MPositionXY> CreateMPositionXY(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int16_t x = 0,
    int16_t y = 0) {
  MPositionXYBuilder builder_(_fbb);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

struct MPositionXYDir FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MPositionXYDirBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_Y = 6,
    VT_DIRECTION = 8
  };
  int16_t x() const {
    return GetField<int16_t>(VT_X, 0);
  }
  int16_t y() const {
    return GetField<int16_t>(VT_Y, 0);
  }
  GameProtocol::Direction direction() const {
    return static_cast<GameProtocol::Direction>(GetField<int8_t>(VT_DIRECTION, 0));
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int16_t>(verifier, VT_X, 2) &&
           VerifyField<int16_t>(verifier, VT_Y, 2) &&
           VerifyField<int8_t>(verifier, VT_DIRECTION, 1) &&
           verifier.EndTable();
  }
};

struct MPositionXYDirBuilder {
  typedef MPositionXYDir Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x(int16_t x) {
    fbb_.AddElement<int16_t>(MPositionXYDir::VT_X, x, 0);
  }
  void add_y(int16_t y) {
    fbb_.AddElement<int16_t>(MPositionXYDir::VT_Y, y, 0);
  }
  void add_direction(GameProtocol::Direction direction) {
    fbb_.AddElement<int8_t>(MPositionXYDir::VT_DIRECTION, static_cast<int8_t>(direction), 0);
  }
  explicit MPositionXYDirBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MPositionXYDir> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MPositionXYDir>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MPositionXYDir> CreateMPositionXYDir(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int16_t x = 0,
    int16_t y = 0,
    GameProtocol::Direction direction = GameProtocol::Direction_UP) {
  MPositionXYDirBuilder builder_(_fbb);
  builder_.add_y(y);
  builder_.add_x(x);
  builder_.add_direction(direction);
  return builder_.Finish();
}

struct CSLogin FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CSLoginBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           verifier.EndTable();
  }
};

struct CSLoginBuilder {
  typedef CSLogin Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(CSLogin::VT_NAME, name);
  }
  explicit CSLoginBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CSLogin> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CSLogin>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CSLogin> CreateCSLogin(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0) {
  CSLoginBuilder builder_(_fbb);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CSLogin> CreateCSLoginDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return GameProtocol::CreateCSLogin(
      _fbb,
      name__);
}

struct CSPlayerMoveRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CSPlayerMoveRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DIRECTION = 4,
    VT_MESSEGEID = 6
  };
  GameProtocol::Direction direction() const {
    return static_cast<GameProtocol::Direction>(GetField<int8_t>(VT_DIRECTION, 0));
  }
  GameProtocol::EPacketProtocol messegeid() const {
    return static_cast<GameProtocol::EPacketProtocol>(GetField<int32_t>(VT_MESSEGEID, 201));
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_DIRECTION, 1) &&
           VerifyField<int32_t>(verifier, VT_MESSEGEID, 4) &&
           verifier.EndTable();
  }
};

struct CSPlayerMoveRequestBuilder {
  typedef CSPlayerMoveRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_direction(GameProtocol::Direction direction) {
    fbb_.AddElement<int8_t>(CSPlayerMoveRequest::VT_DIRECTION, static_cast<int8_t>(direction), 0);
  }
  void add_messegeid(GameProtocol::EPacketProtocol messegeid) {
    fbb_.AddElement<int32_t>(CSPlayerMoveRequest::VT_MESSEGEID, static_cast<int32_t>(messegeid), 201);
  }
  explicit CSPlayerMoveRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CSPlayerMoveRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CSPlayerMoveRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CSPlayerMoveRequest> CreateCSPlayerMoveRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    GameProtocol::Direction direction = GameProtocol::Direction_UP,
    GameProtocol::EPacketProtocol messegeid = GameProtocol::EPacketProtocol_CS_PlayerMoveRequest) {
  CSPlayerMoveRequestBuilder builder_(_fbb);
  builder_.add_messegeid(messegeid);
  builder_.add_direction(direction);
  return builder_.Finish();
}

struct SCPlayerMoveResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SCPlayerMoveResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DIRECTION = 4,
    VT_MESSEGEID = 6
  };
  GameProtocol::Direction direction() const {
    return static_cast<GameProtocol::Direction>(GetField<int8_t>(VT_DIRECTION, 0));
  }
  GameProtocol::EPacketProtocol messegeid() const {
    return static_cast<GameProtocol::EPacketProtocol>(GetField<int32_t>(VT_MESSEGEID, 202));
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_DIRECTION, 1) &&
           VerifyField<int32_t>(verifier, VT_MESSEGEID, 4) &&
           verifier.EndTable();
  }
};

struct SCPlayerMoveResponseBuilder {
  typedef SCPlayerMoveResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_direction(GameProtocol::Direction direction) {
    fbb_.AddElement<int8_t>(SCPlayerMoveResponse::VT_DIRECTION, static_cast<int8_t>(direction), 0);
  }
  void add_messegeid(GameProtocol::EPacketProtocol messegeid) {
    fbb_.AddElement<int32_t>(SCPlayerMoveResponse::VT_MESSEGEID, static_cast<int32_t>(messegeid), 202);
  }
  explicit SCPlayerMoveResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SCPlayerMoveResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SCPlayerMoveResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SCPlayerMoveResponse> CreateSCPlayerMoveResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    GameProtocol::Direction direction = GameProtocol::Direction_UP,
    GameProtocol::EPacketProtocol messegeid = GameProtocol::EPacketProtocol_SC_PlayerMoveResponse) {
  SCPlayerMoveResponseBuilder builder_(_fbb);
  builder_.add_messegeid(messegeid);
  builder_.add_direction(direction);
  return builder_.Finish();
}

struct CSPlayerAttackRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CSPlayerAttackRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TARGET_ID = 4,
    VT_DIRECTION = 6,
    VT_MESSEGEID = 8
  };
  int32_t target_id() const {
    return GetField<int32_t>(VT_TARGET_ID, 0);
  }
  GameProtocol::Direction direction() const {
    return static_cast<GameProtocol::Direction>(GetField<int8_t>(VT_DIRECTION, 0));
  }
  GameProtocol::EPacketProtocol messegeid() const {
    return static_cast<GameProtocol::EPacketProtocol>(GetField<int32_t>(VT_MESSEGEID, 205));
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_TARGET_ID, 4) &&
           VerifyField<int8_t>(verifier, VT_DIRECTION, 1) &&
           VerifyField<int32_t>(verifier, VT_MESSEGEID, 4) &&
           verifier.EndTable();
  }
};

struct CSPlayerAttackRequestBuilder {
  typedef CSPlayerAttackRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_target_id(int32_t target_id) {
    fbb_.AddElement<int32_t>(CSPlayerAttackRequest::VT_TARGET_ID, target_id, 0);
  }
  void add_direction(GameProtocol::Direction direction) {
    fbb_.AddElement<int8_t>(CSPlayerAttackRequest::VT_DIRECTION, static_cast<int8_t>(direction), 0);
  }
  void add_messegeid(GameProtocol::EPacketProtocol messegeid) {
    fbb_.AddElement<int32_t>(CSPlayerAttackRequest::VT_MESSEGEID, static_cast<int32_t>(messegeid), 205);
  }
  explicit CSPlayerAttackRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CSPlayerAttackRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CSPlayerAttackRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CSPlayerAttackRequest> CreateCSPlayerAttackRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t target_id = 0,
    GameProtocol::Direction direction = GameProtocol::Direction_UP,
    GameProtocol::EPacketProtocol messegeid = GameProtocol::EPacketProtocol_CS_PlayerAttackRequest) {
  CSPlayerAttackRequestBuilder builder_(_fbb);
  builder_.add_messegeid(messegeid);
  builder_.add_target_id(target_id);
  builder_.add_direction(direction);
  return builder_.Finish();
}

struct SCPlayerAttackResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SCPlayerAttackResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TARGET_ID = 4,
    VT_DIRECTION = 6,
    VT_HP = 8,
    VT_EXP = 10,
    VT_MESSEGEID = 12
  };
  int32_t target_id() const {
    return GetField<int32_t>(VT_TARGET_ID, 0);
  }
  GameProtocol::Direction direction() const {
    return static_cast<GameProtocol::Direction>(GetField<int8_t>(VT_DIRECTION, 0));
  }
  int32_t HP() const {
    return GetField<int32_t>(VT_HP, 0);
  }
  int32_t exp() const {
    return GetField<int32_t>(VT_EXP, 0);
  }
  GameProtocol::EPacketProtocol messegeid() const {
    return static_cast<GameProtocol::EPacketProtocol>(GetField<int32_t>(VT_MESSEGEID, 206));
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_TARGET_ID, 4) &&
           VerifyField<int8_t>(verifier, VT_DIRECTION, 1) &&
           VerifyField<int32_t>(verifier, VT_HP, 4) &&
           VerifyField<int32_t>(verifier, VT_EXP, 4) &&
           VerifyField<int32_t>(verifier, VT_MESSEGEID, 4) &&
           verifier.EndTable();
  }
};

struct SCPlayerAttackResponseBuilder {
  typedef SCPlayerAttackResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_target_id(int32_t target_id) {
    fbb_.AddElement<int32_t>(SCPlayerAttackResponse::VT_TARGET_ID, target_id, 0);
  }
  void add_direction(GameProtocol::Direction direction) {
    fbb_.AddElement<int8_t>(SCPlayerAttackResponse::VT_DIRECTION, static_cast<int8_t>(direction), 0);
  }
  void add_HP(int32_t HP) {
    fbb_.AddElement<int32_t>(SCPlayerAttackResponse::VT_HP, HP, 0);
  }
  void add_exp(int32_t exp) {
    fbb_.AddElement<int32_t>(SCPlayerAttackResponse::VT_EXP, exp, 0);
  }
  void add_messegeid(GameProtocol::EPacketProtocol messegeid) {
    fbb_.AddElement<int32_t>(SCPlayerAttackResponse::VT_MESSEGEID, static_cast<int32_t>(messegeid), 206);
  }
  explicit SCPlayerAttackResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SCPlayerAttackResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SCPlayerAttackResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SCPlayerAttackResponse> CreateSCPlayerAttackResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t target_id = 0,
    GameProtocol::Direction direction = GameProtocol::Direction_UP,
    int32_t HP = 0,
    int32_t exp = 0,
    GameProtocol::EPacketProtocol messegeid = GameProtocol::EPacketProtocol_SC_PlayerAttackResponse) {
  SCPlayerAttackResponseBuilder builder_(_fbb);
  builder_.add_messegeid(messegeid);
  builder_.add_exp(exp);
  builder_.add_HP(HP);
  builder_.add_target_id(target_id);
  builder_.add_direction(direction);
  return builder_.Finish();
}

struct CSPlayerChattingRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CSPlayerChattingRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MESSAGE = 4,
    VT_MESSEGEID = 6
  };
  const ::flatbuffers::String *message() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MESSAGE);
  }
  GameProtocol::EPacketProtocol messegeid() const {
    return static_cast<GameProtocol::EPacketProtocol>(GetField<int32_t>(VT_MESSEGEID, 301));
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_MESSAGE) &&
           verifier.VerifyString(message()) &&
           VerifyField<int32_t>(verifier, VT_MESSEGEID, 4) &&
           verifier.EndTable();
  }
};

struct CSPlayerChattingRequestBuilder {
  typedef CSPlayerChattingRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_message(::flatbuffers::Offset<::flatbuffers::String> message) {
    fbb_.AddOffset(CSPlayerChattingRequest::VT_MESSAGE, message);
  }
  void add_messegeid(GameProtocol::EPacketProtocol messegeid) {
    fbb_.AddElement<int32_t>(CSPlayerChattingRequest::VT_MESSEGEID, static_cast<int32_t>(messegeid), 301);
  }
  explicit CSPlayerChattingRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CSPlayerChattingRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CSPlayerChattingRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CSPlayerChattingRequest> CreateCSPlayerChattingRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> message = 0,
    GameProtocol::EPacketProtocol messegeid = GameProtocol::EPacketProtocol_CS_PlayerChattingRequest) {
  CSPlayerChattingRequestBuilder builder_(_fbb);
  builder_.add_messegeid(messegeid);
  builder_.add_message(message);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CSPlayerChattingRequest> CreateCSPlayerChattingRequestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *message = nullptr,
    GameProtocol::EPacketProtocol messegeid = GameProtocol::EPacketProtocol_CS_PlayerChattingRequest) {
  auto message__ = message ? _fbb.CreateString(message) : 0;
  return GameProtocol::CreateCSPlayerChattingRequest(
      _fbb,
      message__,
      messegeid);
}

struct SCPlayerChattingResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SCPlayerChattingResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_MESSAGE = 6,
    VT_MESSEGEID = 8
  };
  int32_t id() const {
    return GetField<int32_t>(VT_ID, 0);
  }
  const ::flatbuffers::String *message() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MESSAGE);
  }
  GameProtocol::EPacketProtocol messegeid() const {
    return static_cast<GameProtocol::EPacketProtocol>(GetField<int32_t>(VT_MESSEGEID, 302));
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_ID, 4) &&
           VerifyOffset(verifier, VT_MESSAGE) &&
           verifier.VerifyString(message()) &&
           VerifyField<int32_t>(verifier, VT_MESSEGEID, 4) &&
           verifier.EndTable();
  }
};

struct SCPlayerChattingResponseBuilder {
  typedef SCPlayerChattingResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(int32_t id) {
    fbb_.AddElement<int32_t>(SCPlayerChattingResponse::VT_ID, id, 0);
  }
  void add_message(::flatbuffers::Offset<::flatbuffers::String> message) {
    fbb_.AddOffset(SCPlayerChattingResponse::VT_MESSAGE, message);
  }
  void add_messegeid(GameProtocol::EPacketProtocol messegeid) {
    fbb_.AddElement<int32_t>(SCPlayerChattingResponse::VT_MESSEGEID, static_cast<int32_t>(messegeid), 302);
  }
  explicit SCPlayerChattingResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SCPlayerChattingResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SCPlayerChattingResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SCPlayerChattingResponse> CreateSCPlayerChattingResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> message = 0,
    GameProtocol::EPacketProtocol messegeid = GameProtocol::EPacketProtocol_SC_PlayerChattingResponse) {
  SCPlayerChattingResponseBuilder builder_(_fbb);
  builder_.add_messegeid(messegeid);
  builder_.add_message(message);
  builder_.add_id(id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SCPlayerChattingResponse> CreateSCPlayerChattingResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t id = 0,
    const char *message = nullptr,
    GameProtocol::EPacketProtocol messegeid = GameProtocol::EPacketProtocol_SC_PlayerChattingResponse) {
  auto message__ = message ? _fbb.CreateString(message) : 0;
  return GameProtocol::CreateSCPlayerChattingResponse(
      _fbb,
      id,
      message__,
      messegeid);
}

struct CSRandomTeleportRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CSRandomTeleportRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MESSEGEID = 4
  };
  GameProtocol::EPacketProtocol messegeid() const {
    return static_cast<GameProtocol::EPacketProtocol>(GetField<int32_t>(VT_MESSEGEID, 401));
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_MESSEGEID, 4) &&
           verifier.EndTable();
  }
};

struct CSRandomTeleportRequestBuilder {
  typedef CSRandomTeleportRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_messegeid(GameProtocol::EPacketProtocol messegeid) {
    fbb_.AddElement<int32_t>(CSRandomTeleportRequest::VT_MESSEGEID, static_cast<int32_t>(messegeid), 401);
  }
  explicit CSRandomTeleportRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CSRandomTeleportRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CSRandomTeleportRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CSRandomTeleportRequest> CreateCSRandomTeleportRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    GameProtocol::EPacketProtocol messegeid = GameProtocol::EPacketProtocol_CS_RandomTeleportRequest) {
  CSRandomTeleportRequestBuilder builder_(_fbb);
  builder_.add_messegeid(messegeid);
  return builder_.Finish();
}

}  // namespace GameProtocol

#endif  // FLATBUFFERS_GENERATED_GAMEPROTOCOL_GAMEPROTOCOL_H_
